# Generated by Django 4.2 on 2023-06-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_autor_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='descricao',
            new_name='nome',
        ),
    ]
